kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: echoheaders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoheaders
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.8
        ports:
        - name: 8080
          containerPort: 8080
