#!/bin/bash
# Deploy script run during continuous deploy.

## Arguments
GKE_CLUSTER="$1"
PROJECT="$2"
FLAVOR="$3"
DRY_RUN="$4"

if [ -z "$GKE_CLUSTER" ] || [ -z "$FLAVOR" ] || [ -z "$DRY_RUN" ]; then
  echo "required parameters: gke-cluster(ops-prod/ops-prod-dmz), flavor(canary/stable), dry-run(blank/--dry-run=false)" >&2
  exit 1
fi

## Invariants
REGION=us-central1

gcloud auth activate-service-account --key-file=${GOOGLE_APPLICATION_CREDENTIALS}

gcloud container clusters get-credentials "${GKE_CLUSTER}" --project "${PROJECT}" --region "${REGION}"

bundle install

bundle exec kdt deploy \
  --context "gke_${PROJECT}_${REGION}_${GKE_CLUSTER}" \
  --artifact "${GKE_CLUSTER}" \
  --flavor "${FLAVOR}" \
  "$DRY_RUN"
