apiVersion: v1
kind: Service
metadata:
  name: http-svc
  namespace: jenkins-promotion-poc
  labels:
    app: http-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: echoheaders 
